const DS_DON_VI = {
    "Trung tâm Kinh doanh VNPT Hà Nội (VNPT)": [
        "CHGD 165 Cầu Giấy",
        "CHGD 30 Phạm Hùng",
        "CHGD Ngãi Cầu",
        "CHGD Ngô Gia Tự",
        "CHGD 604 Hà Huy Tập",
        "CHGD Mê Linh",
        "CHGD Chi Đông",
        "CHGD Đông Hội",
        "CHGD Thị trấn Đông Anh",
        "CHGD Hòa Thạch",
        "CHGD 197 Nguyễn Đức Thuận",
        "CHGD Vinhomes Oceanpark",
        "CHGD 36 Phạm Văn Đồng",
        "CHGD VNPT Phúc Thọ",
        "CHGD 75 Đinh Tiên Hoàng",
        "CHGD Phú Xuyên",
        "CHGD Chúc Sơn",
        "CHGD Mỹ Đức",
        "CHGD số 10 Tạ Quang Bửu",
        "CHGD Times City",
        "CHGD số 811 Giải Phóng",
        "CHGD số 161 Ngọc Hồi",
        "CHGD số 297 Tây Sơn",
        "CHGD số 5 Ô Chợ Dừa",
        "CHGD số 138 Trung Kính",
        "CHGD Tòa nhà Internet",
        "CHGD 664 Lạc Long Quân",
        "CHGD CT1 Mễ Trì",
        "CHGD TT Sóc Sơn",
        "CHGD Hoài Đức",
        "CHGD Đan Phượng",
        "CHGD Đông Mỹ",
        "CHGD 79 Thụy Khuê",
        "CHGD 171 Mai Hắc Đế",
        "CHGD VNPT Mới Quốc oai",
        "CHGD VNPT Thạch Thất",
        "CHGD Thường Tín",
        "CHGD VNPT Xuân Mai",
        "CHGD Thanh Oai",
        "CHGD Ứng Hòa",
        "CHGD 57 Huỳnh Thúc Kháng",
        "CHGD Nguyễn Trãi",
        "CHGD 97 Nguyễn Chí Thanh",
        "CHGD 51Vũ Trọng Phụng",
        "CHGD VNPT Ba Vì",
        "CHGD VNPT Sơn Tây",
        "CHGD VNPT Hòa Lạc",
        "CHGD Cầu Bươu",
        "CHGD Ngọc Lâm",
        "CHGD Nguyễn Thái Học",
    ],
    "Công ty Dịch vụ MobiFone Khu vực I (Mobifone)": [
        "Cửa hàng Đông Anh",
        "Cửa hàng 61 Minh Khai",
        "CHGD MobiFone H. Ba Vì",
        "Cửa hàng MobiFone TX Sơn Tây",
        "CHGD MobiFone H. Phúc Thọ",
        "CHGD H. Ứng Hòa",
        "Cửa hàng 80 Hàng Mã",
        "Cửa hàng 55 Xuân La",
        "Cửa hàng 228 Nguyễn Văn Cừ",
        "Cửa hàng 432 Hồ Tùng Mậu",
        "Cửa hàng 9 Nguyễn Văn Huyên",
        "Cửa hàng 70 Trung Hoà",
        "Cửa hàng 827 Quang Trung Hà Đông",
        "Cửa hàng 22 Lê Đức Thọ",
        "Cửa hàng 270 Lạc Trung",
        "Cửa hàng 669 Giải Phóng",
        "Cửa hàng Long Biên",
        "Cửa hàng Gia Lâm",
        "CHGD H. Sóc Sơn",
        "Cửa hàng Chúc Sơn - Chương Mỹ",
        "Cửa hàng Xuân Mai - Chương Mỹ",
        "CHGD H. Thạch Thất",
        "CHGD MobiFone Quốc Oai",
        "CHGD H. Phú Xuyên",
        "Cửa hàng Thường Tín",
        "CHGD H. Mỹ Đức",
        "Cửa hàng Thanh Oai",
        "Cửa hàng Thanh Trì",
        "Cửa hàng 124 Trần Phú",
        "Cửa hàng 368 Nguyễn Trãi",
        "Cửa hàng 101 Đội Cấn",
        "Cửa hàng Hoài Đức (Trạm Trôi)",
        "Cửa hàng Đan Phượng",
        "Cửa hàng 244 Thụy Khuê",
        "Cửa hàng 588 Hà Huy Tập Gia Lâm",
        "Cửa hàng An Khánh Hoài Đức",
        "Cửa hàng 172 Vĩnh Hưng",
        "Cửa hàng 104 Bạch Đằng",
        "Cửa hàng 120 Tân Mai Hà Nội",
        "Cửa hàng giao dịch Huyện Mê Linh",
        "Cửa hàng Phù Lỗ Sóc Sơn",
        "Số 6 Sa Đôi Nam Từ Liêm Hà Nội",
        "Cửa hàng 97 Nguyễn Chí Thanh",
        "Cửa hàng 213 Xã Đàn",
    ],
    "Công ty TNHH Nhà nước MTV TM & XNK Viettel (Viettel Store)": [
        "HNI05",
        "HNI02",
        "HNI03",
        "HNI04",
        "HNI11",
        "HNI14",
        "HNI19",
        "HNI21",
        "HNI22",
        "HNI23",
        "HNI24",
        "HNI26",
        "HNI08",
        "HNI12",
        "HNI16",
        "HNI15",
        "HNI07",
        "HNI01",
        "HNI13",
        "HNI17",
        "HNI18",
        "HNI10",
        "HNI09",
        "HNI20",
        "HNI92",
        "HNI06",
    ],
    "Công ty cổ phần bán lẻ kỹ thuật số FPT (FPT Retail)": [
        "FPT Shop Hải Bối",
        "FPT Shop 155 Vân Trì",
        "FPT Shop Tiền Phong Mê Linh",
        "FPT Long Châu 130 Tỉnh Lộ 419, Liên Quan",
        "FPT Long Châu 61 + 63 TL420, Thạch Hòa",
        "FPT Shop Tản Lĩnh",
        "FPT Shop số 05 Hàng Giấy",
        "Long Châu Thôn Kim Thượng, Kim Lũ",
        "Long Châu 44 Đại Nghiệp, Tân Dân",
        "Long Châu Thôn Trung Oai, Phúc Thịnh",
        "Long Châu Chợ Kim",
        "Long Châu số 6 Giáp Hải",
        "FPT Shop 299 Trung Kính",
        "FPTShop 637 Quang Trung",
        "FPTShop Tầng 1 TTTM Chợ Bưởi",
        "FPT Shop 8 Láng Hạ",
        "FPT Shop 216 Thái Hà",
        "FPTShop 495A Trương Định",
        "Long Châu Xóm 7, Cấn Thượng",
        "FPT Shop 162 Phố Tía",
        "Long Châu 1 Thanh Ninh, Tân Dân",
        "FPT Shop 787 Chùa Tổng",
        "Long Châu Ngã 4 Chợ Cá, Tân Tiến",
        "FPT Shop 70 Quang Trung Vân Đình",
        "Long Châu Thôn Đông Viên, Hữu Văn",
        "FPT Shop 01 Thôn Dốc Lã",
        "Long Châu Khu D, Tổ 5, Sóc Sơn",
        "Long Châu 60A Phù Lỗ",
        "FPT Shop Mai Đình - Sóc Sơn",
        "FPT Shop 2 Núi Đôi",
        "Thôn Cao Trung, Đức Giang",
        "FPT Shop 109 Tây Sơn - Phùng",
        "FPT Shop 237 Xuân Phương",
        "FPTShop 79B Kim Ngưu",
        "FPT Long Châu 99 - 101 Quảng Oai",
        "FPT Shop Khu Mới - Thạch Thất",
        "FPT Shop 03 Nguyễn Thái Học",
        "FPT Shop 15 Chùa Thông",
        "FPTShop 267 Hoàng Hoa Thám",
        "FPTShop 10-12 Cầu Diễn",
        "Long Châu 269 Phố Ga",
        "Long Châu 1 Hùng Nguyên, Thường Tín",
        "FPT Shop 228 Phố Ga",
        "Long Châu Thôn Lam Điền, Chương Mỹ",
        "Long Châu Chợ Phượng, Phụng Châu",
        "Long Châu số 7-9-11 Bắc Sơn",
        "FPT Shop Xóm Nội Chúc Sơn",
        "FPT Shop 55 Đại Đồng",
        "Long Châu 251 Bình Đà",
        "FPT Shop Lưu Phái Ngũ Hiệp",
        "FPT Shop 482 Ngọc Hồi",
        "Long Châu Thôn Trung Thịnh",
        "Long Châu Thôn Dư Xá, Hòa Nam",
        "FPT Shop 438 Khương Đình",
        "FPT Shop 186 Đào Xuyên - Đa Tốn",
        "FPTShop 45 Thái Hà",
        "FPTShop 10 Nguyễn Xiển",
        "Long Châu Thôn Đoài",
        "FPT Shop Tiểu Khu Mỹ Lâm",
        "Long Châu 106-108 Ngô Xuân Quảng",
    ],
    "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)": [
        "PGD Lộc Hà",
        "CN Đông Hà Nội",
        "CN Long Biên Hà Nội",
        "PGD Hồng Tiến",
        "PGD Gia Hưng",
        "PGD Vĩnh Ngọc",
        "PGD Kim Chung",
        "CN Quang Minh",
        "PGD Phù Lỗ",
        "PGD Sóc Sơn",
        "PGD Đức Giang",
        "PGD Việt Hưng",
        "PGD Vạn Xuân",
        "CN Hoài Đức",
        "CN Vạn Phúc Hà Nội",
        "PGD An Khánh",
        "PGD Cầu Diễn",
        "CN Gia Lâm",
        "CN Tây Hồ",
        "PGD Lạc Long Quân",
        "PGD Nhật Chiêu",
        "PGD Phạm Văn Đồng",
        "PGD Nghĩa Đô",
        "PGD Phùng Chí Kiên",
        "PGD Nguyễn Văn Huyên",
        "PGD Làng Quốc Tế Thăng Long",
        "PGD Nghĩa Tân",
        "CN Bắc Hà",
        "PGD Starlake",
        "PGD Liên Hà",
        "PGD Kim Mã",
        "PGD D2 Giảng Võ",
        "PGD Bắc Thành Công",
        "PGD Bà Triệu",
        "CN Hà Thành",
        "PGD Tháp Hà Nội",
        "CN Tràng Tiền - Hà Nội",
        "CN Thành Công - Hà Nội",
        "PGD Văn Phú",
        "PGD An Hưng",
        "PGD Lê Trọng Tấn",
        "PGD 90 Nguyễn Tuân",
        "CN Thanh Xuân",
        "CN Thái Hà",
        "PGD Xa La",
        "PGD Yết Kiêu",
        "PGD Trần Phú",
        "PGD Ngô Thì Nhậm Hà Đông",
        "PGD Triều Khúc",
        "PGD Định Công",
        "PGD Tôn Thất Tùng",
        "PGD Khương Mai",
        "PGD Bắc Linh Đàm",
        "PGD Hoà Bình",
        "PGD Lạc Trung",
        "PGD Cầu Dền",
        "CN Sở Giao dịch 1",
        "PGD Sun City",
        "PGD BIDV Ba Vì",
        "PGD BIDV Thạch Thất",
        "PGD BIDV Thị trấn Liên Quan",
        "PGD Thành Sơn - CN Sơn Tây (BIDV)",
        "PGD BIDV Lê Lợi",
        "PGD BIDV Trung Sơn Trầm",
        "PGD BIDV Xuân Khanh",
        "PGD BIDV Hòa Lạc",
        "PGD BIDV West Lake",
        "CN Hai Bà Trưng",
        "PGD Tây Sơn",
        "PGD Lương Định Của",
        "PGD 99 Láng Hạ",
        "PGD Viet Tower",
        "PGD Yên Lãng",
        "PGD Sông Hồng",
        "CN Ba Đình",
        "PGD Ô Chợ Dừa",
        "PGD Hào Nam",
        "CN Hoàn Kiếm",
        "PGD Hàng Vôi",
        "PGD Hàng Giấy",
        "PGD Thuốc Bắc",
        "PGD Hàng Chiếu",
        "PGD Hàng Đậu",
        "PGD Lý Nam Đế",
        "PGD Hàng Bông",
        "CN Sở Giao dịch 3",
        "PGD Tôn Đức Thắng",
        "PGD Khâm Thiên",
        "PGD Vincom Village",
        "CN Thành Đô",
        "PGD Vân Trì",
        "PGD Vũ Tông Phan",
        "PGD Trường Chinh",
        "PGD Khu đô Thị Yên Hoà",
        "PGD Trung Kính",
        "PGD Nhân Chính",
        "CN Đông Đô",
        "PGD Trung Hoà",
        "PGD Madarin",
        "PGD Nguyễn Chí Thanh",
        "PGD Thủ Lệ",
        "PGD Vương Thừa Vũ",
        "CN Tràng An",
        "PGD Nam Từ Liêm",
        "CN Mỹ Đình",
        "PGD Gardenia",
        "PGD Nguyễn Cơ Thạch",
        "PGD Phạm Hùng",
        "CN Từ Liêm",
        "PGD The Manor",
        "PGD Lê Đức Thọ",
        "PGD Mễ Trì",
        "PGD Nguyễn Hoàng",
        "PGD Đồng Tâm",
        "PGD Tam Trinh",
        "PGD Minh Khai",
        "PGD Tân Mai",
        "CN Nam Hà Nội",
        "PGD Đại Kim",
        "PGD Đô Thị Hoàng Mai",
        "PGD Chúc Sơn",
        "PGD Thanh Hà",
        "PGD Ngọc Hồi",
        "PGD Tecco Garden",
        "PGD Nguyễn Thái Học",
        "CN Thăng Long",
        "PGD Trần Quý Kiên",
        "PGD Nguyễn Phong Sắc",
        "CN Cầu Giấy",
        "PGD Detech Tower",
        "CN BIDV Ngọc Khánh Hà Nội",
        "PGD Tuệ Tĩnh",
        "CN Hà Nội",
        "PGD Lý Thái Tổ",
        "PGD Đinh Lễ",
        "PGD Hàng Chuối",
        "CN Hà Đông",
        "PGD Nguyễn Trãi",
        "PGD Văn Quán",
        "PGD Tố Hữu",
        "PGD Green Bay",
        "PGD Lê Hồng Phong",
        "PGD Xuân La",
        "PGD Ngọc Lâm",
        "PGD Ngọc Thuỵ",
        "PGD Gia Thuỵ",
        "PGD Nội Bài",
        "PGD Đan Phượng",
        "PGD Nam Thăng Long",
        "PGD Thành Trung",
        "PGD Ocean Park",
        "PGD Nhật Tân",
        "PGD Hồ Tây",
        "PGD Hoàng Quốc Việt",
        "PGD 138B Giảng Võ",
        "CN Đống Đa",
        "PGD Nam Cao",
        "PGD Cửa Nam",
        "PGD Trung tâm",
        "PGD Royal City",
        "PGD Thanh Xuân Bắc",
        "PGD Nguyễn Tuân",
        "PGD Nguyễn Thanh Bình",
        "CN Hoàng Mai Hà Nội",
        "PGD Linh Đàm",
        "PGD Times City",
        "PGD Bình Minh",
        "PGD Trần Đại Nghĩa",
        "PGD Hinode",
        "PGD Bách Khoa",
        "PGD Ngô Thì Nhậm",
        "CN Quang Trung",
        "PGD Lê Đại Hành",
        "PGD Phố Huế",
        "PGD Phúc Thọ",
        "PGD Ngoại Giao Đoàn",
        "PGD Kosmo Tây Hồ",
        "PGD Tân Xuân",
        "PGD Phương Liên",
        "PGD Khương Thượng",
        "PGD Kim Liên",
        "PGD Vĩnh Hồ",
        "PGD Cát Linh",
        "PGD Đường Thành",
        "PGD Giao Lưu",
        "PGD Nguyễn Chánh",
        "PGD Grand Plaza",
        "PGD Nguyễn Khang",
        "PGD Nam Trung Yên",
        "PGD Trung Yên",
        "PGD Láng Thượng",
        "PGD Nam Thành Công",
        "PGD 268 Đội Cấn",
        "PGD Ngọc Hà",
        "PGD Nguyễn An Ninh",
        "PGD Chu Văn An",
        "PGD Vạn Bảo",
        "PGD Điện Biên Phủ",
        "PGD Nguyễn Trường Tộ",
        "PGD Phan Đình Phùng",
        "PGD Cửa Bắc",
        "PGD Dịch Vọng",
        "PGD Dương Đình Nghệ",
        "PGD Duy Tân",
        "PGD Thành Thái",
        "Chi nhánh Hồng Hà",

    ],
    "Tổng công ty Bưu chính Viettel (Viettel Post)": [
        "Bưu cục Mỹ Đức",
        "Bưu cục Hà Đông",
        "Bưu cục Tây Nam Linh Đàm",
        "Bưu cục Lý Thái Tổ",
        "Bưu cục Bách Khoa",
        "Bưu cục Thạch Bàn",
        "Bưu cục Võng Xuyên",
        "Bưu cục Thường Tín",
        "Bưu cục Mễ Trì Thượng",
        "Bưu cục Trạm Trôi",
        "Kho vùng HN05",
        "Bưu cục Bắc Đuống",
        "Bưu Cục Tiền Phong 2",
        "Bưu cục Sóc Sơn 1",
        "Bưu cục Hoàng Quốc Việt",
        "Bưu cục Quốc Oai",
        "Bưu cục Thạch Thất",
        "Bưu cục Sơn Tây",
        "Bưu cục Ba Vì",
        "Bưu cục Phú Xuyên",
        "Bưu cục Chúc Sơn",
        "Bưu cục Thanh Oai",
        "Bưu cục Ứng Hòa",
        "Bưu cục Tây Hồ 1",
        "Bưu cục Phúc Diễn",
        "Bưu cục Thanh Liệt",
        "Bưu cục Nguyễn Tuân",
    ],
    "Tổng công ty Bưu điện Việt Nam (VN Post)": [
        "Bưu cục Tây Mỗ",
        "Bưu cục Đan Phượng",
        "Bưu cục Đức Giang",
        "Bưu cục Kim Anh",
        "Bưu cục Hoài Đức",
        "Bưu cục Đô thị Định Công",
        "Bưu cục Bắc Linh Đàm",
        "Bưu cục Ba Vì",
        "Bưu cục Sài Đồng",
        "Bưu cục Phú Xuyên",
        "Bưu cục Phú Minh",
        "Bưu cục Giải Phóng",
        "Bưu cục Thường Tín",
        "Bưu cục VN Post Chương Mỹ",
        "Bưu cục Mỹ Đức",
        "Bưu cục Giao dịch Trung tâm",
        "Bưu cục Lạc Long Quân",
        "Bưu cục Thăng Long",
        "Bưu cục Đống Đa",
        "Bưu cục Thanh Xuân",
        "Bưu cục Hà Đông",
        "Bưu cục Yên Phụ",
        "Bưu cục Hoàng Cầu",
        "Bưu cục Chợ Mơ",
        "Bưu cục Quốc Oai",
        "Bưu cục Gia Lâm",
        "Bưu cục Nguyễn Cơ Thạch",
        "Bưu cục Thanh Oai",
        "Bưu cục Khương Đình",
        "Bưu cục Cầu Giấy",
        "Bưu cục Đông Anh",
        "Bưu cục Mê Linh",
        "Bưu cục Ngã Ba Dâu",
        "Bưu cục Nhổn",
        "Bưu cục Ngãi Cầu",
        "Bưu cục Xuân Phương",
        "Bưu cục Sơn Lộc",
        "Bưu cục VN Post Quốc Oai",
        "Bưu cục VN Post Phúc Thọ",
        "Bưu cục Trung Hòa",
        "Bưu cục Doãn Kế Thiện",
        "Bưu cục Cầu Diễn 2",
        "Bưu cục Cầu Bươu",
        "Bưu cục Thanh Trì",
        "Bưu cục Ứng Hòa",
        "Bưu cục Đốc Ngữ",
        "Bưu cục Kim Liên",
        "Bưu cục Láng Trung",
        "Bưu cục VN Post Thạch Thất",
        "Bưu cục Sơn Tây",
        "Bưu cục Tiền Phong",
        "Bưu cục Sóc Sơn",
        "Bưu cục Nghĩa Tân",
        "Bưu cục Trần Hưng Đạo",
        "Bưu cục Khương Mai",
        "Bưu cục Hoàn Kiếm",
        "Bưu cục La Khê",
    ],
};


const DANH_MUC_TTHC = {
    "Xây dựng": [
        "Cấp giấy phép xây dựng mới đối với công trình cấp III, cấp IV (Công trình không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án) và nhà ở riêng lẻ",
        "Cấp giấy phép xây dựng sửa chữa, cải tạo đối với công trình cấp III, cấp IV (công trình Không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án) và nhà ở riêng lẻ",
        "Cấp điều chỉnh giấy phép xây dựng đối với công trình cấp III, cấp IV (công trình Không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án) và nhà ở riêng lẻ",
        "Gia hạn giấy phép xây dựng đối với công trình cấp III, cấp IV (công trình Không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Sửa chữa, cải tạo/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án) và nhà ở riêng lẻ",
        "Cấp lại giấy phép xây dựng đối với công trình cấp III, cấp IV (công trình Không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Sửa chữa, cải tạo/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án) và nhà ở riêng lẻ",
        "Cấp giấy phép xây dựng mới công trình cấp đặc biệt, cấp I, cấp II (Công trình không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án)",
        "Cấp giấy phép xây dựng sửa chữa, cải tạo đối với công trình cấp đặc biệt, cấp I, cấp II (công trình Không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án)",
        "Cấp điều chỉnh giấy phép xây dựng đối với công trình cấp đặc biệt, cấp I, cấp II (công trình Không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án)",
        "Gia hạn giấy phép xây dựng đối với công trình cấp đặc biệt, cấp I, cấp II (Không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Sửa chữa, cải tạo/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án)",
        "Cấp lại giấy phép xây dựng đối với công trình cấp đặc biệt, cấp I, cấp II (công trình Không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Sửa chữa, cải tạo/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án)",
        "Cấp giấy phép di dời đối với công trình cấp đặc biệt, cấp I và cấp II (Công trình không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án)",
        "Cấp giấy phép di dời đối với công trình cấp cấp III, cấp IV (công trình Không theo tuyến/Theo tuyến trong đô thị/Tín ngưỡng, tôn giáo/Tượng đài, tranh hoành tráng/Theo giai đoạn cho công trình không theo tuyến/Theo giai đoạn cho công trình theo tuyến trong đô thị/Dự án) và nhà ở riêng lẻ"
    ],
    "Lý lịch tư pháp": [
        "Cấp phiếu lý lịch tư pháp qua ứng dụng VNeID",
        "Cấp Phiếu lý lịch tư pháp cho công dân Việt Nam, người nước ngoài đang cư trú tại Việt Nam"
    ],
    "Đường bộ": [
        "Cấp lại Giấy phép xe tập lái",
        "Cấp lại Giấy phép lái xe",
        "Đổi Giấy phép lái xe do ngành Giao thông vận tải cấp"
    ],
    "Văn bằng, chứng chỉ": [
        "Cấp bản sao văn bằng, chứng chỉ từ sổ gốc"
    ],
    "Quảng cáo": [
        "Thủ tục tiếp nhận hồ sơ thông báo sản phẩm quảng cáo trên bảng quảng cáo, băng-rôn"
    ],
    "Khoa học, Công nghệ, Môi trường và Khuyến nông": [
        "Đăng ký công bố hợp quy đối với các sản phẩm, hàng hóa sản xuất trong nước được quản lý bởi các quy chuẩn kỹ thuật quốc gia do Bộ Nông nghiệp và Phát triển nông thôn ban hành"
    ],
    "Xúc tiến thương mại": [
        "Thông báo hoạt động khuyến mại"
    ],
    "Quy hoạch xây dựng, kiến trúc": [
        "Cung cấp thông tin về quy hoạch xây dựng thuộc thẩm quyền của UBND cấp tỉnh",
        "Cung cấp thông tin về quy hoạch xây dựng thuộc thẩm quyền của UBND cấp huyện"
    ],
    "Quản lý chất lượng nông lâm sản và thủy sản": [
        "Cấp Giấy chứng nhận cơ sở đủ điều kiện an toàn thực phẩm đối với cơ sở sản xuất, kinh doanh thực phẩm nông, lâm, thủy sản"
    ],
    "Lao động, tiền lương, quan hệ lao động": [
        "Đăng ký nội quy lao động của doanh nghiệp"
    ],
    "Xuất bản": [
        "Cấp giấy phép nhập khẩu xuất bản phẩm không kinh doanh"
    ],
    "Thông tin điện tử": [
        "Cấp giấy chứng nhận đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng",
        "Sửa đổi, bổ sung Giấy chứng nhận đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng",
        "Gia hạn Giấy chứng nhận đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng",
        "Cấp lại Giấy chứng nhận đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng"
    ],
    "An toàn thực phẩm và dinh dưỡng": [
        "Cấp giấy chứng nhận cơ sở đủ điều kiện an toàn thực phẩm đối với cơ sở sản xuất thực phẩm, kinh doanh dịch vụ ăn uống thuộc thẩm quyền của Ủy ban nhân dân cấp tỉnh",
        "Cấp Giấy Chứng nhận cơ sở đủ điều kiện an toàn thực phẩm đối với cơ sở sản xuất thực phẩm, kinh doanh dịch vụ ăn uống thuộc thẩm quyền của UBND cấp tỉnh (đối với cơ sở kinh doanh dịch vụ ăn uống phục vụ dưới 200 suất ăn)"
    ],
    "Thành lập và hoạt động hộ kinh doanh": [
        "Đăng ký thành lập hộ kinh doanh",
        "Đăng ký thay đổi nội dung đăng ký hộ kinh doanh",
        "Cấp lại nội dung đăng ký hộ kinh doanh",
        "Tạm ngừng hoạt động hộ kinh doanh, tiếp tục kinh doanh trước thời hạn đã thông báo của hộ kinh doanh",
        "Chấm dứt hoạt động hộ kinh doanh"
    ],
    "Hộ tịch": [
        "Cấp bản sao trích lục hộ tịch",
        "Đăng ký khai sinh",
        "Đăng ký kết hôn",
        "Đăng ký khai tử",
        "Cấp Giấy xác nhận tình trạng hôn nhân",
        "Thay đổi, cải chính, bổ sung thông tin hộ tịch",
        "Thủ tục thay đổi, cải chính, bổ sung hộ tịch, xác định lại dân tộc"
    ],
    "Bảo trợ xã hội": [
        "Hỗ trợ chi phí mai táng cho đối tượng bảo trợ xã hội"
    ],
    "Khám bệnh, chữa bệnh": [
        "Cấp mới giấy phép hành nghề trong giai đoạn chuyển tiếp đối với hồ sơ nộp từ ngày 01/01/2024 đến thời điểm kiểm tra đánh giá năng lực hành nghề đối với các chức danh bác sĩ, y sĩ, điều dưỡng, hộ sinh, kỹ thuật y, dinh dưỡng lâm sàng, cấp cứu viên ngoại viện, tâm lý lâm sàng - Trường hợp người lần đầu tiên cấp giấy phép hành nghề quy định tại điểm a, điểm b khoản 1 Điều 30 của Luật Khám bệnh - Hội đồng bác sĩ",
        "Cấp mới giấy phép hành nghề trong giai đoạn chuyển tiếp đối với hồ sơ nộp từ ngày 01/01/2024 đến thời điểm kiểm tra đánh giá năng lực hành nghề đối với các chức danh bác sĩ, y sĩ, điều dưỡng, hộ sinh, kỹ thuật y, dinh dưỡng lâm sàng, cấp cứu viên ngoại viện, tâm lý lâm sàng - Trường hợp người lần đầu tiên cấp giấy phép hành nghề quy định tại điểm a, điểm b khoản 1 Điều 30 của Luật Khám bệnh - Hội đồng các chức danh còn lại"
    ],
    "Dược": [
        "Cấp lần đầu và cấp giấy chứng nhận đủ điều kiện kinh doanh dược đối với trường hợp bị thu hồi Giấy chứng nhận đủ điều kiện kinh doanh dược thuộc thẩm quyền của Sở Y tế"
    ],
    "Đăng ký biện pháp bảo đảm": [
        "Đăng ký biện pháp bảo đảm bằng quyền sử dụng đất, quyền sở hữu nhà ở và tài sản khác gắn liền với đất",
        "Xóa đăng ký biện pháp bảo đảm bằng quyền sử dụng đất, tài sản gắn liền với đất"
    ],
    "Chứng thực": [
        "Chứng thực bản sao điện tử từ bản chính"
    ],
    "Đầu tư tại Việt Nam": [
        "Thủ tục cấp Giấy chứng nhận đăng ký đầu tư đối với dự án không thuộc diện chấp thuận chủ trương đầu tư"
    ],
    "Cư trú": [
        "Đăng ký tạm trú",
        "Đăng ký thường trú",
        "Xác nhận thông tin về cư trú"
    ],
    "Căn cước": [
        "Cấp đổi thẻ căn cước",
        "Cấp thẻ căn cước cho người từ đủ 14 tuổi trở lên"
    ],
    "Việc làm": [
        "Cấp giấy phép lao động cho người lao động nước ngoài làm việc tại Việt Nam"
    ],
    "Đăng ký, quản lý phương tiện giao thông cơ giới đường bộ": [
        "Đăng ký, cấp biển số xe lần đầu"
    ]
};
